
server:
    error:
        include-stacktrace: on_param
spring:
    datasource:
        driver-class-name: org.h2.Driver
        password: ''
        url: jdbc:h2:mem:<agenda-api>
        username: sa
    h2:
        console:
            enabled: true
            path: /h2
    jpa:
        hibernate:
            ddl-auto: update
        database-platform:
          org.hibernate.dialect.H2Dialect
